import { RatioType } from './graphql.js';

export const origworld = {
  name: 'Cecil Stedman',
  logo: 'icones/monde-gda.jpg',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: '',
  products: [
    {
      id: 1,
      name: 'Patrouilles de quartier',
      logo: 'icones/p1-patrouilles.jpg',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Premiers costumes', logo: 'icones/p1-premiers-costumes.jpg', seuil: 20, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Alerte radio GDA', logo: 'icones/p1-alerte-radio.jpg', seuil: 75, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Soutien de la police locale', logo: 'icones/p1-soutien-police.jpg', seuil: 200, idcible: 1, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 2,
      name: 'Missions du Teen Team',
      logo: 'icones/p2-teen-team.jpg',
      cout: 50,
      croissance: 1.1,
      revenu: 12,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Uniformes coordonnés', logo: 'icones/p2-uniformes.jpg', seuil: 25, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Base secrète', logo: 'icones/p2-base-secrete.jpg', seuil: 100, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Reconnaissance médiatique', logo: 'icones/p2-mediatique.jpg', seuil: 300, idcible: 2, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 3,
      name: 'Opérations des Guardians of the Globe',
      logo: 'icones/p3-guardians.jpg',
      cout: 600,
      croissance: 1.12,
      revenu: 130,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'QG des Guardians', logo: 'icones/p3-qg.jpg', seuil: 30, idcible: 3, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Entraînement intensif', logo: 'icones/p3-entrainement.jpg', seuil: 120, idcible: 3, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Statut de héros national', logo: 'icones/p3-heros-national.jpg', seuil: 350, idcible: 3, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 4,
      name: 'Black-ops de la GDA',
      logo: 'icones/p4-blackops.jpg',
      cout: 6000,
      croissance: 1.13,
      revenu: 1400,
      vitesse: 45000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Autorisation de Cecil', logo: 'icones/p4-autorisation.jpg', seuil: 35, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: "Réseau d'informateurs", logo: 'icones/p4-informateurs.jpg', seuil: 150, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Budget noir approuvé', logo: 'icones/p4-budget-noir.jpg', seuil: 400, idcible: 4, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 5,
      name: 'Alliance atlante',
      logo: 'icones/p5-atlantide.jpg',
      cout: 60000,
      croissance: 1.14,
      revenu: 15000,
      vitesse: 90000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Premier contact', logo: 'icones/p5-premier-contact.jpg', seuil: 40, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Technologie sous-marine', logo: 'icones/p5-techno-sous-marine.jpg', seuil: 175, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Traité officiel', logo: 'icones/p5-traite.jpg', seuil: 450, idcible: 5, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 6,
      name: 'Programme de veille Viltrumite',
      logo: 'icones/p6-viltrumite.jpg',
      cout: 600000,
      croissance: 1.16,
      revenu: 160000,
      vitesse: 180000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Signal capté', logo: 'icones/p6-signal-capte.jpg', seuil: 45, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Alerte Coalition', logo: 'icones/p6-alerte-coalition.jpg', seuil: 200, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Confinement stabilisé', logo: 'icones/p6-confinement.jpg', seuil: 500, idcible: 6, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
  ],
  allunlocks: [
    { name: 'Coalition mondiale des super-héros', logo: 'icones/global-coalition-mondiale.jpg', seuil: 50, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: "Reconnaissance de l'ONU", logo: 'icones/global-onu.jpg', seuil: 250, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Traité intergalactique de défense', logo: 'icones/global-traite-intergalactique.jpg', seuil: 1000, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
  ],
  upgrades: [
    { name: 'Radio à ondes courtes', logo: 'icones/up-radio.jpg', seuil: 800, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Costume renforcé', logo: 'icones/up-costume-renforce.jpg', seuil: 3000, idcible: 1, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Comm GDA chiffrée', logo: 'icones/up-comm-chiffree.jpg', seuil: 8000, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Campagne médiatique nationale', logo: 'icones/up-campagne-mediatique.jpg', seuil: 20000, idcible: 2, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Amélioration exosquelette', logo: 'icones/up-exosquelette.jpg', seuil: 40000, idcible: 3, ratio: 3, typeratio: RatioType.gain, unlocked: false },
    { name: "Satellite d'observation", logo: 'icones/up-satellite.jpg', seuil: 90000, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Renfort logistique GDA', logo: 'icones/up-logistique.jpg', seuil: 300000, idcible: 4, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Sonar atlante longue portée', logo: 'icones/up-sonar.jpg', seuil: 600000, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Sous-marin blindé', logo: 'icones/up-sous-marin.jpg', seuil: 1200000, idcible: 5, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Détecteur de signature Viltrumite', logo: 'icones/up-detecteur.jpg', seuil: 3000000, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
  ],
  angelupgrades: [
    { name: 'Renfort de la Coalition des Planètes', logo: 'icones/ange-renfort-coalition.jpg', seuil: 10, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Technologie volée aux Viltrumites', logo: 'icones/ange-techno-volee.jpg', seuil: 50, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
    { name: 'Alliance avec Thaedus', logo: 'icones/ange-alliance.jpg', seuil: 250, idcible: -1, ratio: 2, typeratio: RatioType.ange, unlocked: false },
    { name: "Réseau d'ambassadeurs interstellaires", logo: 'icones/ange-ambassadeurs.jpg', seuil: 1000, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Pacte de non-agression Viltrumite', logo: 'icones/ange-pacte.jpg', seuil: 5000, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
  ],
  managers: [
    { name: 'Rex Splode', logo: 'icones/mgr-rex.jpg', seuil: 50, idcible: 1, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Atom Eve', logo: 'icones/mgr-eve.jpg', seuil: 800, idcible: 2, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'The Immortal', logo: 'icones/mgr-immortal.jpg', seuil: 8000, idcible: 3, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Cecil Stedman', logo: 'icones/mgr-cecil.jpg', seuil: 80000, idcible: 4, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Aquarus', logo: 'icones/mgr-aquarus.jpg', seuil: 800000, idcible: 5, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: "Allen l'Alien", logo: 'icones/mgr-allen.jpg', seuil: 8000000, idcible: 6, ratio: 0, typeratio: RatioType.gain, unlocked: false },
  ],
};
