import { RatioType } from './graphql.js';

export const origworld = {
  name: 'Cecil Stedman',
  logo: 'icones/gda.jpg',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: '',
  products: [
    {
      id: 1,
      name: 'Patrouilles de quartier',
      logo: 'icones/patrouille.jpg',
      cout: 4,
      croissance: 1.07,
      revenu: 1,
      vitesse: 500,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Premiers costumes', logo: 'icones/patrouille.jpg', seuil: 20, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Alerte radio GDA', logo: 'icones/patrouille.jpg', seuil: 75, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Soutien de la police locale', logo: 'icones/patrouille.jpg', seuil: 200, idcible: 1, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 2,
      name: 'Missions du Teen Team',
      logo: 'icones/teenteam.jpg',
      cout: 60,
      croissance: 1.1,
      revenu: 12,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Uniformes coordonnés', logo: 'icones/teenteam.jpg', seuil: 25, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Base secrète', logo: 'icones/teenteam.jpg', seuil: 100, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Reconnaissance médiatique', logo: 'icones/teenteam.jpg', seuil: 300, idcible: 2, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 3,
      name: 'Opérations des Guardians of the Globe',
      logo: 'icones/guardians.jpg',
      cout: 720,
      croissance: 1.12,
      revenu: 130,
      vitesse: 12000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'QG des Guardians', logo: 'icones/guardians.jpg', seuil: 30, idcible: 3, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Entraînement intensif', logo: 'icones/guardians.jpg', seuil: 120, idcible: 3, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Statut de héros national', logo: 'icones/guardians.jpg', seuil: 350, idcible: 3, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 4,
      name: 'Black-ops de la GDA',
      logo: 'icones/gda-blackops.jpg',
      cout: 8640,
      croissance: 1.13,
      revenu: 1400,
      vitesse: 45000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Autorisation de Cecil', logo: 'icones/gda-blackops.jpg', seuil: 35, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: "Réseau d'informateurs", logo: 'icones/gda-blackops.jpg', seuil: 150, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Budget noir approuvé', logo: 'icones/gda-blackops.jpg', seuil: 400, idcible: 4, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 5,
      name: 'Alliance atlante',
      logo: 'icones/atlantide.jpg',
      cout: 103680,
      croissance: 1.14,
      revenu: 15000,
      vitesse: 90000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Premier contact', logo: 'icones/atlantide.jpg', seuil: 40, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Technologie sous-marine', logo: 'icones/atlantide.jpg', seuil: 175, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Traité officiel', logo: 'icones/atlantide.jpg', seuil: 450, idcible: 5, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
    {
      id: 6,
      name: 'Programme de veille Viltrumite',
      logo: 'icones/viltrumite.jpg',
      cout: 1244160,
      croissance: 1.16,
      revenu: 160000,
      vitesse: 180000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        { name: 'Signal capté', logo: 'icones/viltrumite.jpg', seuil: 45, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Alerte Coalition', logo: 'icones/viltrumite.jpg', seuil: 200, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
        { name: 'Confinement stabilisé', logo: 'icones/viltrumite.jpg', seuil: 500, idcible: 6, ratio: 3, typeratio: RatioType.gain, unlocked: false },
      ],
    },
  ],
  allunlocks: [
    { name: 'Coalition mondiale des super-héros', logo: 'icones/all.jpg', seuil: 50, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: "Reconnaissance de l'ONU", logo: 'icones/all.jpg', seuil: 250, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Traité intergalactique de défense', logo: 'icones/all.jpg', seuil: 1000, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
  ],
  upgrades: [
    { name: 'Radio à ondes courtes', logo: 'icones/patrouille.jpg', seuil: 800, idcible: 1, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Costume renforcé', logo: 'icones/patrouille.jpg', seuil: 3000, idcible: 1, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Comm GDA chiffrée', logo: 'icones/teenteam.jpg', seuil: 8000, idcible: 2, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Campagne médiatique nationale', logo: 'icones/teenteam.jpg', seuil: 20000, idcible: 2, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Amélioration exosquelette', logo: 'icones/guardians.jpg', seuil: 40000, idcible: 3, ratio: 3, typeratio: RatioType.gain, unlocked: false },
    { name: "Satellite d'observation", logo: 'icones/gda-blackops.jpg', seuil: 90000, idcible: 4, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Renfort logistique GDA', logo: 'icones/gda-blackops.jpg', seuil: 300000, idcible: 4, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Sonar atlante longue portée', logo: 'icones/atlantide.jpg', seuil: 600000, idcible: 5, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
    { name: 'Sous-marin blindé', logo: 'icones/atlantide.jpg', seuil: 1200000, idcible: 5, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Détecteur de signature Viltrumite', logo: 'icones/viltrumite.jpg', seuil: 3000000, idcible: 6, ratio: 2, typeratio: RatioType.vitesse, unlocked: false },
  ],
  angelupgrades: [
    { name: 'Renfort de la Coalition des Planètes', logo: 'icones/coalition.jpg', seuil: 10, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Technologie volée aux Viltrumites', logo: 'icones/coalition.jpg', seuil: 50, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
    { name: 'Alliance avec Thaedus', logo: 'icones/coalition.jpg', seuil: 500, idcible: -1, ratio: 2, typeratio: RatioType.ange, unlocked: false },
    { name: "Réseau d'ambassadeurs interstellaires", logo: 'icones/coalition.jpg', seuil: 2000, idcible: 0, ratio: 2, typeratio: RatioType.gain, unlocked: false },
    { name: 'Pacte de non-agression Viltrumite', logo: 'icones/coalition.jpg', seuil: 10000, idcible: 0, ratio: 3, typeratio: RatioType.gain, unlocked: false },
  ],
  managers: [
    { name: 'Rex Splode', logo: 'icones/rexsplode.jpg', seuil: 50, idcible: 1, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Atom Eve', logo: 'icones/atomeve.jpg', seuil: 1000, idcible: 2, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'The Immortal', logo: 'icones/immortal.jpg', seuil: 12000, idcible: 3, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Cecil Stedman', logo: 'icones/cecil.jpg', seuil: 150000, idcible: 4, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: 'Aquarus', logo: 'icones/aquarus.jpg', seuil: 1800000, idcible: 5, ratio: 0, typeratio: RatioType.gain, unlocked: false },
    { name: "Allen l'Alien", logo: 'icones/allen.jpg', seuil: 20000000, idcible: 6, ratio: 0, typeratio: RatioType.gain, unlocked: false },
  ],
};
